module.exports = {
    project :'🏗',
    tasks   :'📁',
    chart   :'📈',
    add     :'➕',
    edit    :'🖊️',
    list    :'📜',
    delete  :'❌',    
    back    :'🔙',
    done    :'✔',
    offer   :'🤝',
    assign  :'🤏',
    man     :'🙍‍♂️',
    woman   :'🙍‍♀️',
    laptop  :'💻',
    save    :'💾',
    home    :'🏠',
    right   :'➡️',
    close   :'🚪',
    left    :'⬅️'
}