/**
 * Generate inline keyboard for reply_markup 
 * ------------------------------------------
 * report format =  {
 *      userId :{
 *          projectId:{
 *              name : string,
 *              task : {
 *                  taskId : {
 *                      name: string,
 *                      status: string,
 *                      time: Date
 *                  }
 *              }
 *          }
 *      }
 * }
 * --------------------------------------------
 * retrun format = [
 *  [
 *    {
 *      text: "keyboard name",
 *      callback_data:"{
 *          "projectId": "projectId",
 *          "taskId": "taskId"
 *      }"
 *    }
 *  ]
 * ]
 * 
 * @param {Object} report 
 * @param {string} userId 
 * @param {string} salt - unique code generated by each new message
 * @returns {Array2D} 
 */
function generateInlineKeyboardFrom(projects, prefix) {
    const inlineKeyboard = []
    const addrs  = {}
    let counter = 0
    for (projectId of Object.keys(projects)) {
        const tasks = projects[projectId].task
        for (taskId of Object.keys(tasks)) {
            let addr = 'select@'+counter
            const keyboardLayout = {
                text: tasks[taskId].name,
                callback_data: `${prefix}-select-${addr}`
            }
            inlineKeyboard.push([keyboardLayout])
            addrs[addr] = {
                projectId,
                taskId
            }
            counter+=1
        }
    }
    inlineKeyboard.push([{
        text: "Report Progress",
        callback_data: `${prefix}-send`
    }, {
        text: "Cancel",
        callback_data: `${prefix}-cancel`
    }])
    return {inlineKeyboard,addrs}
}

/**
 * Report input Format :
 * --------------------------------
 * [{
 *  userID:string,
 *  projectID : string,
 *  status: string,
 *  name: string,
 *  projectName : string,
 *  date : Date,
 *  taskId: string
 * }]
 * ---------------------------------
 * return format =  {
 *      userId :{
 *          projectId:{
 *              name : string,
 *              task : {
 *                  taskId : {
 *                      name: string,
 *                      status: string,
 *                      time: Date
 *                  }
 *              }
 *          }
 *      }
 * }
 * 
 * @param {Array} report 
 * @return {Object} 
 */
function parseToReportFormat(report) {
    const result = {}
    for (let item of report) {
        const { projectID, status, name, projectName, date, taskID, userID } = item
        if(result[userID]===undefined){
            result[userID] = {}
        }
        if(result[userID][projectID]===undefined){
            result[userID][projectID] = {
                name: projectName,
                task: {}
            }
        }
        result[userID][projectID].task[taskID] = {
            name: name,
            status: status,
            time: date
        }
    }
    return result
}

function generateToken(str, salt){
    return Math.random().toString(10).slice(2,6) + `${str}${salt}`
}

module.exports = {
    generateInlineKeyboardFrom,
    parseToReportFormat,
    generateToken,
}


